#ifndef BRAPlatformSpecificDefines_h
#define BRAPlatformSpecificDefines_h

#define BRANativeColor UIColor
#define BRANativeImage UIImage
#define BRANativeFont UIFont
#define BRANativeFontDescriptor UIFontDescriptor
#define BRANativeFontDescriptorSizeAttribute UIFontSizeAttribute
#define BRANativeEdgeInsets UIEdgeInsets
#define BRANativeEdgeInsetsMake UIEdgeInsetsMake
#define BRANativeEdgeInsetsZero UIEdgeInsetsZero
#define BRANativeEdgeInsetsEqualToEdgeInsets UIEdgeInsetsEqualToEdgeInsets
#define BRANativeImagePNGRepresentation UIImagePNGRepresentation
#define BRANativeImageJPEGRepresentation UIImageJPEGRepresentation

#endif /* BRAPlatformSpecificDefines_h */
